spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fornecedor?createDatabaseIfNotExist=true
    password: root
    username: root
